name: flutter_hangman
description: Hangman Game

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  rflutter_alert: ^2.0.7
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf